---
- hosts: docker
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes
    - name: Install docker and docker-compose
      package:
        name:
          - docker.io
          - docker-compose
        state: present
    - name: Add the ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Copy file with owner and permissions
      copy:
        src: static/docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml
        owner: ubuntu
        group: ubuntu
    - name: Run docker-compose stack
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/
